version: 2
jobs:
  build:
    docker:
      - image: dlang2/dmd-circleci

    steps:
      - checkout

      - run:
          name: Build
          command: dub build

      - run:
          name: Test
          command: dub test

      - run:
          name: Print the Current Time
          command: date
